### ISSUE TITLE
Demo rGMS

### ISSUE THREAD

**Issue by interduo** [ZdanowskiS/rGMS#1]
Dasz demo? :)

Nam też to potrzebne -  więc z chęcią wrzucę kilka PR.

**Comment by ZdanowskiS** [comment]
Zgodnie z informacją w README. Nie planuję poświęcać na to czasu bez konkretnego zainteresowania wsparciem rozwoju projektu. Podany jest również bezpośredni kontakt.
Odnośnie demo, tak jak napisałem wyżej.
